"""create tour schedules table

Revision ID: 4f0ed28ac514
Revises: 9fd9f5d20dac
Create Date: 2026-09-26 14:38:03.905339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0ed28ac514'
down_revision: Union[str, Sequence[str], None] = '9fd9f5d20dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_schedules_tour_id'), 'tour_schedules', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_schedules_tour_id'), table_name='tour_schedules')
    op.drop_table('tour_schedules')
    # ### end Alembic commands ###
